root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  #bin = "/opt/homebrew/bin/stdbuf --output=0 ./tmp/main | tee log.txt"
  bin = "./tmp/main 2>&1 | tee log.txt"
  cmd = "bash -c 'go build -o ./tmp/main *.go' && afplay ./assets/ok.wav || afplay ./assets/error.wav"
  delay = 400
  exclude_dir = ["fe", "tmp", "vendor", "testdata", "assets/nsite", "assets/v", "assets/pictures", "assets/pictures/originals" ]
  exclude_file = []
  include_file = ["assets/style.css"]
  exclude_regex = ["_test.go", "*.jpg", "*.png"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  #include_dir = ["assets"]
  #include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "lsnitch"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
